Cep sose2024 main (#10)
* Rhein_Sec NKS imported

* testfiles

* changes to mod.rs's

* updated gitignore

* added adress pub

* Upadated mod.rs, other changes

* added nks_token

* nksError fix

* added exiting methods, other changes

* added api and initialize_module

* provider handle tests auf NksProvider angepasst.

* added RSA encryption and signing

* provider handle test fixes ->
cargo.toml
lib.rs
mod.rs
mod.rs
provider_handle_tests.rs

* provider handle test debug -> keine fehler mehr
"99999" muss durch die echten nks_adress und nks_token ersetzt werden.

* key handle test debug -> ebenfalls keine fehler mehr
"99999" muss durch die echten nks_adress und nks_token ersetzt werden.

* load_key und create_key in nks hcvault provider implementiert

* add current implementation of sign and verify

* fixed imports and other errors

* added errors, added ecc sodium crypto, deleted api.rs, fixed more logic errors, added initial impl for nks config

* minor changes

* minor changes 2

* cfg in key_handle

* cfg in module_provider

* fix delimiter in nks provider and delete unused modules in hcvault mod

* minor changes 3

* fix some errors

* fix url address errors

original error was
error[E0277]: the trait bound &std::option::Option<Url>: IntoUrl is not satisfied --> src/nks/hcvault/key_handle.rs:202:19 | 202 | .post(&self.nks_address) | ---- ^^^^^^^^^^^^^^^^^ the trait IntoUrl is not implemented for &std::option::Option<Url> | | | required by a bound introduced by this call | = help: the following other types implement trait IntoUrl: Url std::string::String &'a str &'a std::string::String

* comment out delete_secrets

is not needed fo tests to run

* comment out delete_secrets + fix url

delete_secrets is not needed for tests to run

* make empty impl of traits

* fix tpm stuff in common key_handle

* change test_matrix to nks in common

* implement initialize_module for nks

* comment out unimplemented tests and fix compilation errors

* implement create_key for nks

* delete unused nks_root_token

* fix cargo

* fit provider parameters to trait declaration

* fix compilation errors

* add getting secrets in initialize_module

* changes to the nks_config, other

* changes to the nksconfig, changes to do_nothing method

* redo overwritten changes

* use config in nks provider

* working test method

* use config in initialize and create_key

* initialize module w/o hardcode but access to config

* add new_token as result of get_and_save_keypair

* test_create_edsa_key and ...ecdh_key

* add private_key and public_key fields to NksProvider. First implementation of load_key

* re-add token.json for persistance after end of runtime

* better client side error handling for when key with id already exists

* reduce duplicate code in provider_handle_tests + impl test_load_ecdsa_key and test_load_ecdh_key

* documentation for provider and provider_handle_tests

* resolve warnings and typos in provider and provider_handle_tests

* remove unused variables in provider

* add match for ecdh in create_key

* remove some outputs used for testing

* Added SigningFailed error

* Implemented Method sign_data, decrypt_data, encrypt_data, verify_signature

* bracket placement

* added SigningFailed to Match

* added test an verify for rsa

* refactored all methods

* refactored all methods

* refactored test_sign_and_verify_rsa and added test_encrypt_and_decrypt_rsa

* made get_config public

* fixed return of decrypt and encrypt and error on verify signature

* fixed matching error if no supported algorithm could be found

* fixed matching error if no supported algorithm could be found

* Fixed Sign and verify test.

* added static base64 decoded rsa keys to test funkction. added base64 decoding of keys

* Fixed test with static base64 encoded keys in key_handle.rs

* changed to port 5000, added https support, changed URLs

* removed unused lib

* added some error handeling, segmented methods

* added static ecc key to sign

* added static ecc key to sign and verify

* added test for ecdsa sign

* fixed RSA key decoding

* working rsa encrypt decrypt

* fixed rsa encrypt decrypt test

* fixed rsa encrypt decrypt test

* add function add_signature_to_secrets

* fixed logic errors, better encrypt decrypt

* functioning encrypt decrypt ecdh

* sign and verify with dalek crate

* remove key creation from signing test

* code clean up, added optional RSA key length

* match hash in sign and verify

* Documentation - key_handle, mod.rs, provider.rs

* Documentation - traits - mod.rs

* remove unnecessary tests

* Add test instructions to README

* dokumentation

* Warnings entfernt

* Error Warnings entfernt

* Added #[Instrument] to all important methods

* Dokumentation Error.rs

---------

Co-authored-by: Phillip Schaefer <2212535@stud.hs.mannheim.de>
Co-authored-by: laurent <laure@LAPTOP-7IUQ1KDP>
Co-authored-by: halrifai <hadirefai@outlook.sa>
Co-authored-by: pl-CJump <3000986@stud.hs-mannheim.de>
Co-authored-by: halrifai <164380470+halrifai@users.noreply.github.com>
Co-authored-by: Phillip Schaefer <2212535@stud.hs-mannheim.de>