fix url address errors
original error was
error[E0277]: the trait bound &std::option::Option<Url>: IntoUrl is not satisfied --> src/nks/hcvault/key_handle.rs:202:19 | 202 | .post(&self.nks_address) | ---- ^^^^^^^^^^^^^^^^^ the trait IntoUrl is not implemented for &std::option::Option<Url> | | | required by a bound introduced by this call | = help: the following other types implement trait IntoUrl: Url std::string::String &'a str &'a std::string::String